config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'pages#homepage'

  resources :articles

  get 'about', to:'pages#about'

  get 'signup', to: 'users#new'

  resources :users, expect: [:new]  
 
  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'
 
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
   belongs_to :user
   validates :title, presence: true, length: {minimum:3, maximum:30}
   validates :description, presence: true, length: {minimum:10, maximum:600}
   validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
    before_save {self.email = email.downcase}
    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 25}


    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 105}, format: { with: VALID_EMAIL_REGEX }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def new
        @article = Article.new
    end

    def index
        @article = Article.paginate(page: params[:page], per_page:5)
    end
    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:success] = "Article has been created succefully"
            redirect_to article_path(@article)
        else
            render :new, status: 422
        end
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:success] = "Artcle has been updated"
            redirect_to article_path(@article)
        else
            render :edit, status: 422
        end    
    end

    def show
        @article = Article.find(params[:id])
    end   
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash[:danger] = "Article was successfuly deleted"
        redirect_to articles_path
    end
    
    private
    def article_params
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def homepage

  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "Loged in successfully"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Incorrect email or password"
            render :new , status: 422    
        end
        
        
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = 'logged out!!'
        redirect_to root_path
    end
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end
    
    def create
       @user = User.new(user_params)
       if @user.save
        flash[:success] = "Welcome to alpha blog #{@user.username}"
        redirect_to articles_path
       else
        render :new, status: 422
       end 
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
         flash[:success] = "your profile has been updated successfully"
         redirect_to articles_path
      else
         render :edit, status: 422
      end
    end

    def show
      @user = User.find(params[:id])
      @user_articles=@user.articles.paginate(page: params[:page],per_page: 5)
    end

    def index
      @user = User.paginate(page: params[:page], per_page: 5)
    end
    
    
    
    

    private
    def user_params
       params.require(:user).permit(:username, :email , :password) 
    end
  
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url,alt: user.username, class:"rounded")
        
    end

    def show_errors(object, field_name)
        if object.errors.any?
          if !object.errors.messages[field_name].blank?
            object.errors.messages[field_name].join(", ")
          end
        end
      end
    
end

app/views/articles/_article.html.erb
<% obj.each do |t| %>
    <div>
        <div class="col-sm-8 offset-sm-2 card card-body bg-light" style="margin-bottom:10px">
            <div class="article-title">
                <%= link_to t.title, article_path(t), style:"text-decoration: none ;" %>
            </div>

            <div class="article-body">
                 <%= truncate(t.description, length: 10 )%>
            </div>
            <div class="article_meta_details">
                <small>
                    created by:  <%= link_to "#{t.user.username}", user_path(t.user) %>  
                    <%= time_ago_in_words(t.created_at) %> ago,
                    <%= time_ago_in_words(t.updated_at) %> ago,
                </small>
            </div>
            <div class="actions"> 
                <%= link_to 'edit', edit_article_path(t), class: "btn btn-sm btn-primary"%>
                <%= link_to 'Delete', article_path(t), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger" %>
            </div>  
        </div>
    </div>                
<% end %>       
  

app/views/articles/_form.html.erb
 
    <div >
        <div class='col-xs-12'>
            <%= form_for @article do |f| %>
                <div class="row mb-3">
                    <div class='col-sm-2 '>
                        <%= f.label :title, class:'col-form-label' %>
                    </div>     
                    <div class='col-sm-10'>    
                        <%= f.text_field :title, class: "form-control" %>
                         <p class='error' style="color:red"><%= show_errors(@article, :title) %></p>
                    </div>
                </div>
                <div class='row mb-3'>
                 <div class="col-sm-2 ">
                <%= f.label :description, class:"col-form-label" %>
                 </div>
                  <div class="col-sm-10">
                <%= f.text_area :description, rows:10, class: "form-control" %>
                 <p class='error' style="color:red"><%= show_errors(@article, :description) %></p>
                  </div>
                </div>
                
                <div class='row mb-3'>
                 <div class="col-sm-10 offset-sm-2">
                  <%= f.submit class:"btn btn-primary" %>
                 </div>
                </div>
                
            <% end %>
            <div class="col-xs-4 offset-sm-5">
            [ <%= link_to 'Cancel and hit back to all articles', articles_path%> ]
            </div>
        </div>
    </div>

app/views/articles/edit.html.erb
<h1 class="center">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">All articles</h1>

 <%= render 'article', obj:@article %>

<div align="center" >
        <%= page_entries_info @article %>
</div>
<br>
<div class="d-flex justify-content-center" >
 <%= will_paginate @article %>
 </div>

app/views/articles/new.erb
<h1> Create a new article </h1>

 <%= form_for @article do |f| %>
    <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
    </p>
    <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
    </p>
    <p>
    
    <%= f.submit %>
    </p>

    
<% end %>

app/views/articles/new.html.erb
<h1 class="center"> Create a new article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %> </h2>
    <div class="card card-body bg-light col-sm-8 offset-sm-2">
        <h4 class="center "><strong>Description:</strong></h4>
        <hr>
        <%= simple_format(@article.description) %>
    
       <div class="actions"> 
            <%= link_to 'edit', edit_article_path(@article), class: "btn btn-sm btn-primary"%>
            <%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger" %>
            <%= link_to 'view all articles', articles_path, class: "btn btn-sm btn-success" %>
       </div>    
    </div>
    <h4>Created by:</h4><br>
     <div class="user-username">
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                <%= link_to @article.user.username, user_path(@article.user), style:"text-decoration: none ;" %>
            </div>

            <div class="user-body">
                 <%= @article.user.email%>
                 <%= pluralize(@article.user.articles.count,"article") if @article.user.articles%>
            </div>

app/views/layouts/_footer.html.erb
<div class='container'>
    <footer class='footer'>
        <small>
            Copyright &copy; <a href='#'>www..com</a>
            by <a href='#'>M SHOKR</a>
        </small>
        <nav>
            <ul>
                <li>
                 <%= link_to 'About', about_path%>
                </li>
            </ul>
        </nav>    
    </footer>
</div>    

app/views/layouts/_messages.html.erb
<div style="margin-top:10px;">
   <div class="col-sm-8 offset-sm-2">
        <% flash.each do |name, msg| %>
        <div class='alert alert-<%= "#{name}" %>'>
        <%# <a href="#" class="close" aria-label="Close" data-dismiss="alert">&#215;</a> %>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
   </div>
</div> 
 
  
  <%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" id=m >
  <div class="container-fluid">
    <%= link_to 'Alpha blog', root_path, class: 'navbar', id: 'logo'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "articles", articles_path, class: "nav-link", aria_current:"page" %>
        </li>
        <li class="nav-item">
          <%= link_to 'New article', new_article_path, class:"nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Actions
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'New article', new_article_path, class:"dropdown-item"%></li>

            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
           <%= link_to 'Logout', logout_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },class:"nav-link"%>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navbar'%>
  <%= render 'layouts/messages'%>
  <div class='container'>
    <%= yield %>
  </div>
  <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Second about</h1>

<%= link_to 'Homepage', root_path %>

app/views/pages/homepage.html.erb
<div class="center mt-4 p-5 bg-primary text-white rounded jumpotron">
    <h1>Homepage</h1>
    <%= link_to 'Sign up now', 'signup',class: "btn btn-danger btn-lg signup" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div>
    <div class="col-sm-6 offset-sm-4">
    <div class="alert alert-danger">
        <div class="panel-heading">
        <h2 class="panel-title">
        <%= pluralize(obj.errors.count, "error") %>
        </h2>
        <div class="panel-body">
            <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
                </ul>
        </div>
        </div>
    </div>
    </div>   
</div> 
    
<% end %>

app/views/users/_form.html.erb
    <div>
        <div class='col-xs-12'>
            <%= form_for @user do |f| %>
                <div class="row mb-3">
                    <div class='col-sm-2 '>
                        <%= f.label :username, class:'col-form-label' %>
                    </div>     
                    <div class='col-sm-10'>    
                        <%= f.text_field :username, class: "form-control" %>
                        <p class='error' style="color:red"><%= show_errors(@user, :username) %></p>

                    </div>
                </div>
                <div class='row mb-3'>
                 <div class="col-sm-2 ">
                <%= f.label :email, class:"col-form-label" %>
                 </div>
                  <div class="col-sm-10">
                <%= f.email_field :email, class: "form-control" %>
                 <p class='error' style="color:red"><%= show_errors(@user, :email) %></p>
                  </div>
                </div>
                <div class='row mb-3'>
                 <div class="col-sm-2 ">
                <%= f.label :password, class:"col-form-label" %>
                 </div>
                  <div class="col-sm-10">
                <%= f.password_field :password, class: "form-control" %>
                 <p class='error' style="color:red"><%= show_errors(@user, :password) %></p>
                  </div>
                </div>
                
                <div class='row mb-3'>
                 <div class="col-sm-10 offset-sm-2">
                  <%= f.submit(@user.new_record? ? "Sign up" : "Update" , class:"btn btn-primary offset-sm-4") %>
                 </div>
                </div>
                
            <% end %>
          
        </div>
    </div>

app/views/users/edit.html.erb
<h1 align="center">Update your profile</h1>
<%= render "form"%>

app/views/users/index.html.erb
<h1 align="center">All users</h1>

<% @user.each do |t| %>
    <div>
        <div class="col-sm-8 offset-sm-2 card card-body bg-light" style="margin-bottom:10px">
            <div class="user-username">
            <%= link_to gravatar_for(t), user_path(t) %>
                <%= link_to t.username, user_path(t), style:"text-decoration: none ;" %>
            </div>

            <div class="user-body">
                 <%= t.email%><br>
                 <%= pluralize(t.articles.count,"article") if t.articles%>
            </div>
        
            <div class="actions"> 
                <%= link_to 'edit', edit_user_path(t), class: "btn btn-sm btn-primary"%>
                <%= link_to 'Delete', user_path(t), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger" %>
            </div>  
        </div>
    </div>                
<% end %>  
<div align="center" >
        <%= page_entries_info @user %>
</div>
<br>
<div class="d-flex justify-content-center" >
 <%= will_paginate @user %>
 </div>     
  

app/views/users/new.html.erb
<h1 align="center">Sign up for Alpha blog</h1>

<%= render "form"%>

app/views/users/show.html.erb
<div>

<h2 align="center"> <%= @user.username %> </h2>

<div class="col-sm-4 offset-sm-4 center">
<%= gravatar_for @user%>
</div>
</div>
    <div class="card card-body bg-light col-sm-8 offset-sm-2">
       <div class="actions"> 
            <%= link_to 'edit', edit_user_path(@user), class: "btn btn-sm btn-primary"%>
            <%= link_to 'Delete', user_path(@user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger" %>
            <%= link_to 'view all users', users_path, class: "btn btn-sm btn-success" %>
       </div>
          <hr>
           <h4 class="center "><strong>here's all <%= @user.username %> articles </strong></h4>

    </div>

    <%= render 'articles/article', obj:@user_articles %>
    <div align="center" >
        <%= page_entries_info @user_articles %>
</div>
<br>
<div class="d-flex justify-content-center" >
 <%= will_paginate @user_articles %>
 </div>  